DROP TABLE Employes CASCADE CONSTRAINT;
DROP TABLE Proposer CASCADE CONSTRAINT;
DROP TABLE Services CASCADE CONSTRAINT;
DROP TABLE Locations CASCADE CONSTRAINT;
DROP TABLE Bungalows CASCADE CONSTRAINT;
DROP TABLE Campings CASCADE CONSTRAINT;
DROP TABLE Clients CASCADE CONSTRAINT;
